In [1]:
import sqlite3
import pandas as pd

In [2]:
conn = sqlite3.connect("company.db")
cursor = conn.cursor()

In [3]:
cursor.execute("""
CREATE TABLE employees (
    emp_id INTEGER PRIMARY KEY,
    name TEXT,
    department TEXT,
    salary INTEGER
)
""")

conn.commit()
print("Table created successfully!")

Table created successfully!

In [4]:
cursor.execute("INSERT INTO employees VALUES (1,'John','HR',50000)")
cursor.execute("INSERT INTO employees VALUES (2,'Alice','IT',70000)")
cursor.execute("INSERT INTO employees VALUES (3,'Bob','Finance',60000)")
cursor.execute("INSERT INTO employees VALUES (4,'David','IT',80000)")

conn.commit()
print("Data inserted successfully!")

Data inserted successfully!

In [5]:
df = pd.read_sql_query(
    "SELECT * FROM employees",
    conn
)

df

   emp_id   name department  salary
0       1   John         HR   50000
1       2  Alice         IT   70000
2       3    Bob    Finance   60000
3       4  David         IT   80000

In [6]:
df = pd.read_sql_query(
    "SELECT * FROM employees WHERE salary > 60000",
    conn
)

df

   emp_id   name department  salary
0       2  Alice         IT   70000
1       4  David         IT   80000

In [8]:
df = pd.read_sql_query(
    "SELECT * FROM employees ORDER BY salary DESC",
    conn
)

df

   emp_id   name department  salary
0       4  David         IT   80000
1       2  Alice         IT   70000
2       3    Bob    Finance   60000
3       1   John         HR   50000

In [9]:
df = pd.read_sql_query(
    """
    SELECT department,
           AVG(salary) AS average_salary
    FROM employees
    GROUP BY department
    """,
    conn
)

df

  department  average_salary
0    Finance         60000.0
1         HR         50000.0
2         IT         75000.0

In [10]:
df = pd.read_sql_query(
    """
    SELECT department,
           AVG(salary) AS average_salary
    FROM employees
    GROUP BY department
    """,
    conn
)

df

  department  average_salary
0    Finance         60000.0
1         HR         50000.0
2         IT         75000.0

In [11]:
df = pd.read_sql_query(
    "SELECT MAX(salary) AS highest_salary FROM employees",
    conn
)

df

   highest_salary
0           80000

In [12]:
df = pd.read_sql_query(
    "SELECT MIN(salary) AS lowest_salary FROM employees",
    conn
)

df

   lowest_salary
0          50000

In [13]:
df = pd.read_sql_query(
    "SELECT COUNT(*) AS total_employees FROM employees",
    conn
)

df

   total_employees
0                4

In [14]:
df = pd.read_sql_query(
    "SELECT SUM(salary) AS total_salary FROM employees",
    conn
)

df

   total_salary
0        260000

In [15]:
df = pd.read_sql_query(
    "SELECT * FROM employees WHERE name LIKE 'A%'",
    conn
)

df

   emp_id   name department  salary
0       2  Alice         IT   70000

In [16]:
df = pd.read_sql_query(
    "SELECT * FROM employees WHERE salary BETWEEN 50000 AND 70000",
    conn
)

df

   emp_id   name department  salary
0       1   John         HR   50000
1       2  Alice         IT   70000
2       3    Bob    Finance   60000

In [17]:
cursor.execute(
    "UPDATE employees SET salary = 75000 WHERE name = 'John'"
)

conn.commit()

print("Salary updated successfully!")

Salary updated successfully!

In [18]:
df = pd.read_sql_query(
    "SELECT * FROM employees",
    conn
)

df

   emp_id   name department  salary
0       1   John         HR   75000
1       2  Alice         IT   70000
2       3    Bob    Finance   60000
3       4  David         IT   80000

In [19]:
cursor.execute(
    "DELETE FROM employees WHERE name = 'Bob'"
)

conn.commit()

print("Record deleted successfully!")

Record deleted successfully!

In [20]:
df = pd.read_sql_query(
    "SELECT * FROM employees",
    conn
)

df

   emp_id   name department  salary
0       1   John         HR   75000
1       2  Alice         IT   70000
2       4  David         IT   80000

In [21]:
conn.close()

print("Database connection closed successfully!")

Database connection closed successfully!

# Employee Database SQL Analysis

## Objective
To perform SQL operations on employee data using SQLite and Python.

## Operations Performed
- CREATE TABLE
- INSERT records
- SELECT query
- WHERE condition
- ORDER BY
- GROUP BY with AVG()
- MAX()
- MIN()
- COUNT()
- SUM()
- LIKE
- BETWEEN
- UPDATE
- DELETE

## Conclusion
Successfully implemented and analyzed employee data using SQL queries and SQLite database.